# Generated by Django 4.0.4 on 2022-05-02 19:31

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ImagenCarrusel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=70)),
                ('texto', models.CharField(max_length=200)),
                ('imagen', models.ImageField(default=None, upload_to='carrusel')),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=70)),
                ('subtitulo', models.CharField(max_length=140)),
                ('cuerpo', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField()),
                ('autor', models.CharField(max_length=50)),
                ('img_portada', models.ImageField(blank=True, null=True, upload_to='portadas_blog')),
                ('img_miniatura', models.ImageField(blank=True, null=True, upload_to='miniaturas_blog')),
                ('fuente', models.CharField(blank=True, max_length=20, null=True)),
                ('link_noticia', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProductoEstrella',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=50)),
                ('imagen', models.ImageField(default=None, upload_to='productos_estrella')),
                ('descripcion', models.TextField()),
            ],
        ),
    ]
