# Generated by Django 4.0.4 on 2022-04-12 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=70)),
                ('subtitulo', models.CharField(max_length=140)),
                ('cuerpo', models.TextField()),
                ('fecha_creacion', models.DateTimeField()),
                ('autor', models.CharField(max_length=50)),
                ('img_portada', models.ImageField(default='portadadefault.jpg', upload_to='portadas')),
                ('img_miniatura', models.ImageField(default='miniaturadefault.jpg', upload_to='miniaturas')),
            ],
        ),
    ]
