# Generated by Django 4.0.3 on 2022-04-30 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppBlog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productoestrella',
            name='descripcion',
            field=models.TextField(default='algo'),
            preserve_default=False,
        ),
    ]
