# Generated by Django 4.0.4 on 2022-04-13 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppBlog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImagenCarrusel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=70)),
                ('texto', models.CharField(max_length=200)),
                ('imagen', models.ImageField(upload_to='carrusel')),
            ],
        ),
        migrations.CreateModel(
            name='ProductoEstrella',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=50)),
                ('imagen', models.ImageField(upload_to='productos_estrella')),
            ],
        ),
        migrations.AddField(
            model_name='post',
            name='fuente',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='link_noticia',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='img_miniatura',
            field=models.ImageField(default='miniaturadefault.jpg', upload_to='miniaturas_blog'),
        ),
        migrations.AlterField(
            model_name='post',
            name='img_portada',
            field=models.ImageField(default='portadadefault.jpg', upload_to='portadas_blog'),
        ),
    ]
