# Generated by Django 4.0.4 on 2022-04-19 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppBlog', '0002_imagencarrusel_productoestrella_post_fuente_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='img_miniatura',
            field=models.ImageField(default='miniaturablogdefault.jpg', upload_to='miniaturas_blog'),
        ),
        migrations.AlterField(
            model_name='post',
            name='img_portada',
            field=models.ImageField(default='portadablogdefault.jpg', upload_to='portadas_blog'),
        ),
    ]
