# Generated by Django 4.0.4 on 2022-04-22 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppBlog', '0003_alter_post_cuerpo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='img_miniatura',
            field=models.ImageField(upload_to='miniaturas_blog'),
        ),
        migrations.AlterField(
            model_name='post',
            name='img_portada',
            field=models.ImageField(upload_to='portadas_blog'),
        ),
    ]
