# Generated by Django 4.0.4 on 2022-04-22 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppBlog', '0004_alter_post_img_miniatura_alter_post_img_portada'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='img_miniatura',
            field=models.ImageField(blank=True, null=True, upload_to='miniaturas_blog'),
        ),
        migrations.AlterField(
            model_name='post',
            name='img_portada',
            field=models.ImageField(blank=True, null=True, upload_to='portadas_blog'),
        ),
    ]
