# Generated by Django 4.0.3 on 2022-04-25 23:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppBlog', '0003_alter_post_img_miniatura_alter_post_img_portada'),
        ('AppBlog', '0005_alter_post_fecha_creacion_alter_post_img_miniatura_and_more'),
    ]

    operations = [
    ]
