# Generated by Django 4.0.4 on 2022-04-25 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppBlog', '0006_merge_20220425_1428'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='img_miniatura',
            field=models.ImageField(blank=True, null=True, upload_to='miniaturas_blog'),
        ),
        migrations.AlterField(
            model_name='post',
            name='img_portada',
            field=models.ImageField(blank=True, null=True, upload_to='portadas_blog'),
        ),
    ]
