# Generated by Django 4.0.4 on 2022-04-25 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppBlog', '0008_alter_imagencarrusel_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagencarrusel',
            name='imagen',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='carrusel'),
        ),
    ]
