# Generated by Django 4.0.4 on 2022-04-25 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppBlog', '0009_alter_imagencarrusel_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagencarrusel',
            name='imagen',
            field=models.ImageField(blank=True, default='imgcarruseldefault.jpg', null=True, upload_to='carrusel'),
        ),
        migrations.AlterField(
            model_name='productoestrella',
            name='imagen',
            field=models.ImageField(blank=True, default='imgestrelladefault.jpg', null=True, upload_to='productos_estrella'),
        ),
    ]
