# Generated by Django 4.0.4 on 2022-04-27 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppBlog', '0010_alter_imagencarrusel_imagen_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagencarrusel',
            name='imagen',
            field=models.ImageField(default=None, upload_to='carrusel'),
        ),
        migrations.AlterField(
            model_name='productoestrella',
            name='imagen',
            field=models.ImageField(default=None, upload_to='productos_estrella'),
        ),
    ]
