# Generated by Django 4.0.4 on 2022-04-25 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppTienda', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operaciones',
            name='fecha_compra',
            field=models.DateField(auto_now=True),
        ),
    ]
